ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=application
      export FLASK_ENV=development
    init: |
      pip install -r requirements.txt
      flask init-db
    command: |
      flask run
vscode:
  extensions:
    - ms-python.python
