version: '3'

services:    
  app:
    build:
      context: ./application
    depends_on:
      - postgres
    ports:
      - 80:5000
    networks:
      - backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/substances?sslmode=disable
  
  postgres:
    image: postgres:alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD:postgres
      POSTGRES_USER:postgres
      POSTGRES_DB:substances
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    networks:
      - backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/substances?sslmode=disable
    depends_on:
      - postgres

networks:
  backend:

volumes:
  postgres:
